import React from 'react';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import FooterContent,{ FooterContentProps } from './components/FooterContent';

const inter = Inter({ subsets: ['latin'] });

interface RootLayoutProps {
  children: React.ReactNode;
  footerProps: FooterContentProps;
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  footerProps,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ padding: '1rem', backgroundColor: '#f0f0f0' }}>
          <h1>我的网站</h1>
          <nav>
            <a href="/" style={{ marginRight: '1rem' }}>首页</a>
            <a href="/about">关于</a>
          </nav>
        </header>

        
          {children}

        <footer style={{ padding: '1rem', backgroundColor: '#f0f0f0', textAlign: 'center' }}>
          <FooterContent {...footerProps} />
        </footer>
      </body>
    </html>
  );
}